# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# SPDX-License-Identifier: MIT

[advisories]
yanked = "deny"

[bans]
multiple-versions = "deny"
wildcards = "deny"

[licenses]
confidence-threshold = 0.93
allow = ["Apache-2.0", "BSL-1.0", "MIT", "Unicode-3.0", "Unlicense"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
